# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92e05af47f49f45d95727a98ff63ac9183cb1d10c90235683c0ea01af64786d9dec85f9e3e949c697f4dd5906aae1b53e12c280d7df1848fdd6adba8c253e9ee

test:
  secret_key_base: 859f5d7a2befeefed5c3af4ab2ad2d51081b3429894d1beef263336c26e951718fdb2a7adc2d0dc309f7a1ff6e87504689047d6ebbf360e54b68c48374c1589c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
